### ISSUE TITLE
Replace glide by Golang dep ?

### ISSUE THREAD

**Issue by euskadi31** [kellabyte/go-benchmarks#2]
In glide readme:

> The Go community now has the dep project to manage dependencies. Please consider trying to migrate from Glide to dep. If there is an issue preventing you from migrating please file an issue with dep so the problem can be corrected. Glide will continue to be supported for some time but is considered to be in a state of support rather than active feature development.

For dep see: https://github.com/golang/dep

Thx

**Comment by kellabyte** [comment]
Dep has also been deprecated for `vgo` I believe. I had issues with dep in another project. It seems like glide is still the most stable option available currently.

**Comment by euskadi31** [comment]
ok :/
