### ISSUE TITLE
doesn't work on a fresh install without manually installing dependencies

### ISSUE THREAD

**Issue by willie** [kellabyte/go-benchmarks#4]
On a machine with none of the dependencies from the root of the repo:

```
$ make hashing
# github.com/kellabyte/go-benchmarks/hashing
hashing/benchmark_test.go:11:2: cannot find package "github.com/OneOfOne/xxhash" in any of:
	/usr/local/Cellar/go/1.10/libexec/src/github.com/OneOfOne/xxhash (from $GOROOT)
	/Users/willie/src/github.com/OneOfOne/xxhash (from $GOPATH)
FAIL	github.com/kellabyte/go-benchmarks/hashing [setup failed]
make: Rscript: No such file or directory
make: *** [hashing] Error 1
```

If I do:

```
$ go get ./...
# github.com/kellabyte/go-benchmarks/http
http/evio.go:24:16: cannot use func literal (type func(int, evio.Info) ([]byte, evio.Options, interface {}, evio.Action)) as type func(int, evio.Info) ([]byte, evio.Options, evio.Action) in assignment
http/evio.go:29:14: cannot use func literal (type func(int, interface {}, []byte) ([]byte, evio.Action)) as type func(int, []byte) ([]byte, evio.Action) in assignment
http/evio.go:37:8: events.NumLoops undefined (type evio.Events has no field or method NumLoops)
```

This solves the problem for the hashing error: `go get -t ./...`, but it doesn't solve the evio part. Maybe you are testing against a different branch?

I'll submit a small PR to add the dependency getting to the makefile.

**Comment by willie** [comment]
https://github.com/kellabyte/go-benchmarks/pull/5

That PR doesn't solve the `evio` problem, though.

**Comment by kellabyte** [comment]
I updated the README because I was missing a documented step but doesn't [this](https://github.com/kellabyte/go-benchmarks#dependencies) install all the required dependencies?

My mistake that I forgot to add it to the README.

**Comment by willie** [comment]
Your documentation fix solves it!

Aside: I hadn't looked for the deps step in the makefile (because I'm not super great with make) and I wouldn't have recognized the glide commands (because I don't use glide for package management).
