### ISSUE TITLE
Create HdrHistogram plot

### ISSUE THREAD

**Issue by kellabyte** [kellabyte/go-benchmarks#6]
I want to be able to plot HdrHistogram output in scripts. The official website does it well but it's javascript only and not easily automated.

[Here](http://hdrhistogram.github.io/HdrHistogram/plotFiles.html) is the official website that lets you plot in the browser.

[Here](https://github.com/HdrHistogram/HdrHistogram/blob/master/GoogleChartsExample/example1.txt) is the HdrHistogram file format.

# Requirements
1. Ability to pass in multiple HdrHistogram files and plot the results.
1. Ability to pass in the percentile range so we can zoom in like the website does.

**Comment by JasonPunyon** [comment]
![image](https://user-images.githubusercontent.com/157782/39649228-1136bcf0-4fb3-11e8-9a21-3cd5d58a7a94.png)


![image](https://user-images.githubusercontent.com/157782/39649174-ddba0fe4-4fb2-11e8-94e4-02a7d80e166c.png)

OK, i have that which looks about right. Do you have a histogram file that has more than one line in it?

**Comment by kellabyte** [comment]
I think we can consider this complete now :) Any bugs or anything we want to change can be logged as enhancements etc.

Thanks SO much!
